### ISSUE TITLE
OutOfMemoryException on some .fbx

### ISSUE THREAD

**Issue by Francoimora** [ikorin24/FbxParser#3]
Hi,

We have OutOfMemoryException occuring when trying to parse some of our .fbx files. Example of a file that gets the exception :

[apo_house_base_01.zip](https://github.com/ikorin24/FbxParser/files/7541590/apo_house_base_01.zip)

Repro code : 

```
try
{
    using (var stream = File.OpenRead("apo_house_base_01.fbx"))
    {
        using (var fbx = FbxParser.Parse(stream))
        {

        }
    }
}
catch (OutOfMemoryException e)
{
    Console.WriteLine("OutOfMemory occured");
}
```

**Comment by ikorin24** [comment]
I'm sorry for the late reply.

First of all, there is no official specification for fbx. This means that I cannot determine if this fbx file is in the correct format or not.

Now I know why this fbx is unreadable. I had assumed that all nodes had a special node called "NULL Record", but your file had a node that did not have it. Since I don't know if this is the correct format, I will not fix this.

However, I was able to import this file in Blender 2.29.0 and load the re-exported fbx file. Give it a try.

If you have additional information, please reply. Thank you.
